language: node_js
node_js:
- node
- '8'
before_deploy: npm run build
deploy:
  provider: pages
  fqdn: xn--z0us92d5wbo6v.xn--v0qr21b.xn--kpry57d
  skip_cleanup: true
  local_dir: build/
  github_token:
    secure: s7bKkQuFikRbdUZfBaQHjglHlNJXL84zELMluGxZ1Qipm0BvaikAQFTpvK50TfitbbwGqlCcIakxRAe8szzI45fxiPeSceH2ng95ziqotU5d+4waaNB0V5W/l+qeHjAnH/PDrdztBTGU2VS4ST2VHesAzQVg5IpkM2x+w9lgU4dQ9HCwnb6F7py2hnzPbuzFe/eBz2pg9NuipKg8FShazGd5FZQc+/1rYsP8bzN9FVLzq5P5F31dzm+TsjjOonHz/uu/CxKkSKj1WSAH3PrKixWXl5xgtuETvW0HYdpm2uzWjMBK+EbOjQOhYBWSka6mm6kEJgFzbSg0GcaT5Chal3XqQ2Vv/FMwF+g/SbSEvAsokdBdMFmY1zrVA5cySZDRHo3c4jK/NG3+MJ9orP0q29x1twG/09f41wBRc5VQho/8Jx1jWzrvSGOdtlc8+7Mmau/3OpAMILucg1DwJXqhfAY4M5EQUSnfT1eh+zd1lxkWAMuGryyqHQwtpzFE+b93hWuoUXYi7qpKchhsR+OJTqxcGIWDvoi1MxGk2OexSxiLi15v1jl5ckDiutGjN2hBm1WGhaqnu1ctg06LOCKxZl6SZel+KmFcqVfv5Np8hHAq3nxil4QKzRTooHCiU/LrveW0LTvVAeaXMteT+5h7FArycIUEY7bAoTWwdhRS/lE=
  on:
    branch: master
